### ISSUE TITLE
Not Ball sapcing

### ISSUE THREAD

**Issue by AdithyaLaakso** [FRC830/2020Robot#5]
Imagine a situation where the driver has a full load of balls and shoots half of them, then maneuvers to the collection center and picks up more balls. This would break the current collection system. This can be solved by running the belt backwards until the balls are out of the snake tube. However, if the tube is empty then the belt will run indefinably. This can be solved one of three ways.

1) a line break sensor that detects when a ball is shot
2) a timer to sense when the belt has run long enough
3) a detector of voltage on the belt to seen when it has run long enough
4) a detector of voltage to detect when the flywheel has shot a ball.

**Comment by reteps** [comment]
is this fixed with the addition of the third line break sensor?

**Comment by reteps** [comment]
driver will use 3rd sensor to keep track.
